# Generated by Django 3.1.2 on 2020-10-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_yandex_checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yandexkassapayment',
            name='period',
        ),
    ]
